### PR TITLE
TRD-853 top 10 broker table

### PR DESCRIPTION
**Pull request by Amir31**
Added top 10 brokers on top as table and made updates for all sub tasks, Waiting for design
https://therealdeal.atlassian.net/jira/software/c/projects/TRD/boards/21?modal=detail&assignee=5cdd92b17aecfb0fea31b149

### CODE REVIEW

**Comment by missionmike** [comment]
@Amir31 when this is ready, please add description/screenshots, tag the requested assignee for review, and set the PR to "ready to review" from draft mode.

**Comment by Amir31** [comment]
Just committed some styling and it is ready to be merged.
We added a table on top for top brokers and few small fixes to previous version

Screenshot 2023-05-22 at 2 19 47 PM

**Comment by missionmike** [comment]
> Just committed some styling and it is ready to be merged. We added a table on top for top brokers and few small fixes to previous version
> 
> Screenshot 2023-05-22 at 2 19 47 PM

Looks great! Love the color separation. Thank you @Amir31

**Review by missionmike — APPROVED** [review]

**Review by missionmike — APPROVED** [review]

**Review by missionmike — APPROVED** [review]

**Review by missionmike — CHANGES_REQUESTED** [review]
Please re-request a review.

**Review by missionmike — APPROVED** [review]

**Pull request merged**
