### PR TITLE
[TRD-3609] Create concept NYC construction project map

### PR DESCRIPTION
**Pull request by trd-yd**
## Summary
The branch contains the HTML and support files for the approved NYC construction jobs (i.e. projects) map. The map allow an user to use a slider to filter the construction jobs by the quarter during which the job was approved.

## Testing Instruction
1. Run a local web server
 ```bash
 npm run serve
 ```
2. Open the NYC approved construction map on a browser using the localhost URL [http://localhost:8080/new-york-city-approved-construction-projects/new-york-city-approved-construction-projects.html](http://localhost:8080/new-york-city-approved-construction-projects/new-york-city-approved-construction-projects.html). Alternately, one can replace `localhost` in the local host URL with the host address that appears in the `npm run serve` output.
   Screenshot 2024-09-10 at 12 49 11 PM
For example, based on the output above, the alternate map URL will be http://192.168.29.11:8080/new-york-city-approved-construction-projects/new-york-city-approved-construction-projects.html.

3. Please wait at least 60 seconds. Confirm that the map, points, legend and slider appear after 60 seconds.
   Screenshot 2024-09-09 at 10 51 47 PM

4. Interact with the slider at the map's bottom center to confirm that the map filters the displayed point.
   4a. Go to the slider.
     Screenshot 2024-09-11 at 11 04 08 AM
   4b. Press and move the slider button to the right. Confirm that the displayed points and filing quarter text change (from `2023Q4` to `2024Q1`).
    Screenshot 2024-09-11 at 11 14 49 AM
   4c. Press and move the button to the right again. Confirm that the displayed points change again and filing quarter text change from `2024Q1 to `2024Q2`.
    Screenshot 2024-09-11 at 11 22 05 AM
   4d. Press and move the button to the right again. Confirm that the displayed points change again and filing quarter text change from `2024Q2 to `2024Q3`.
    Screenshot 2024-09-11 at 11 23 56 AM

     Below is a link to a video show how the slider should work when interacting with it.
 https://github.com/user-attachments/assets/e29b76d3-ee04-4254-b3d2-812a83ff02a8

5. Click on a point to see if the left info panel appears.
   Screenshot 2024-09-10 at 1 01 40 PM

### CODE REVIEW

**Comment by nihalkorkmazz** [comment]
@trd-yd Could you also add how to open the map and add the slider steps into the description?

**Comment by trd-yd** [comment]
> @trd-yd Could you also add how to open the map and add the slider steps into the description?

@nihalkorkmazz, thank you for you input. Please, let me know if I am missing any additional vital information.

**Comment by nihalkorkmazz** [comment]
@trd-yd Overall this looks good, thanks! 2 comments from me:

Can we fix the slider text color on light mode? It is not visible unless you highlight it:

Screenshot 2024-09-11 at 12 36 26 PM

Also on mobile, the slider and the legend element are overlapping. Is there any way to fix it? 

Screenshot 2024-09-11 at 12 40 02 PM

**Comment by trd-yd** [comment]
I made some changes to address the issues you highlighted. I modified the CSS for a better mobile experience
Screenshot 2024-09-11 at 3 11 10 PM

and to better handle light mode.
Screenshot 2024-09-11 at 3 09 22 PM

**Review by nihalkorkmazz — APPROVED** [review]
Thanks for the fix @trd-yd. I think it would look better if the Legend is aligned here on mobile: 

Screenshot 2024-09-12 at 10 48 49 AM

But this is not a blocker, so approving the PR.

**Comment by trd-yd** [comment]
@nihalkorkmazz, thank you for taking your time to review the pull request and provide feedback.

**Pull request merged**
